version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pawaodds-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_KEY=${ADMIN_KEY}
      - TZ=UTC
    depends_on:
      - postgres
    networks:
      - pawaodds_network

  postgres:
    image: postgres:14-alpine
    container_name: pawaodds-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pawauser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your_strong_password_here}
      - POSTGRES_DB=${POSTGRES_DB:-pawaodds}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pawaodds_network

  nginx:
    image: nginx:alpine
    container_name: pawaodds-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - pawaodds_network

  certbot:
    image: certbot/certbot
    container_name: pawaodds-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: renew
    depends_on:
      - nginx

volumes:
  postgres-data:

networks:
  pawaodds_network:
    driver: bridge